annotations:
  catalog.cattle.io/display-name: CRDs for LP Backend
  catalog.cattle.io/namespace: default
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: ezd-crd
  catalog.cattle.io/hidden: "true"
apiVersion: v2
appVersion: 1.2024-19.7
dependencies:
- condition: global.rabbitmq.deploy
  name: rabbitmq-operator
  repository: file://./charts/rabbitmq-operator
  version: 4.0.0
- condition: global.postgresql.deploy
  name: cloudnative-pg
  repository: file://./charts/cloudnative-pg
  version: 0.20.2
- condition: global.redis.deploy
  name: redis-operator
  repository: file://./charts/redis-operator
  version: 0.15.9
description: Set of operators and CRDs for LP Backend
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- ezd
- ezdrp
- ezd-rp
- backend
- databases
kubeVersion: '>=1.19.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: ezd-crd
sources:
- https://github.com/linuxpolska/ezd-rp.git
type: application
version: 1.4.1
