---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.monitoringQueriesConfigMap.name }}
  labels:
    {{- include "cloudnative-pg.labels" . | nindent 4 }}
    cnpg.io/reload: ""
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  queries: {{- toYaml .Values.monitoringQueriesConfigMap.queries | nindent 4 }}
