{{- if .Values.webhook.validating.create }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: cnpg-validating-webhook-configuration
  labels:
    {{- include "cloudnative-pg.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /validate-postgresql-cnpg-io-v1-backup
      port: {{ .Values.service.port }}
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: vbackup.kb.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /validate-postgresql-cnpg-io-v1-cluster
      port: {{ .Values.service.port }}
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: vcluster.kb.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /validate-postgresql-cnpg-io-v1-scheduledbackup
      port: {{ .Values.service.port }}
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: vscheduledbackup.kb.io
  rules:
  - apiGroups:
    - postgresql.cnpg.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledbackups
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /validate-postgresql-cnpg-io-v1-pooler
      port: {{ .Values.service.port }}
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: vpooler.kb.io
  rules:
    - apiGroups:
        - postgresql.cnpg.io
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - poolers
  sideEffects: None
{{- end }}
