# Default values for ezdrp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imageCredentials:
    name: credentials-registry-operator
    registry: "https://index.docker.io/v1/"
    username: ""
    password: ""
    email: ""
  deployment:
    platform: 'kubernetes'
    type: 'custom'
  rabbitmq:
    deploy: true
  postgresql:
    deploy: true
  redis:
    deploy: true

rabbitmq-operator:
  clusterOperator:
    image:
      registry: quay.io
      repository: linuxpolska/ezd-crd_cluster-operator
      tag: 2.9.0-golang-1.22-r1
      pullPolicy: Always
    imagePullSecrets:
    - name: credentials-registry-operator
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 200m
        memory: 500Mi
    tolerations: []
    affinity: {}

  msgTopologyOperator:
    enabled: false


cloudnative-pg:
  image:
    repository: quay.io/linuxpolska/ezd-crd_cloudnative-pg
    tag: 1.23.0-debian-12-r1
    pullPolicy: Always
  imagePullSecrets:
  - name: credentials-registry-operator
  resources: {}
  tolerations: []
  affinity: {}
  podSecurityContext: {}
  fullnameOverride: "postgresql"

redis-operator:
  redisOperator:
    imageName: quay.io/linuxpolska/ezd-crd_redis-operator
    imageTag: 0.18.0-golang-1.21-r1
    pullPolicy: Always
    serviceAccountName: "redis-operator"
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    tolerations: []
    affinity: {}
