annotations:
  catalog.cattle.io/display-name: EZD RP Backend - Apps (2/2)
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: ezd-backend
apiVersion: v2
appVersion: 1.2025.21.7
description: Services necessary to run EZD RP app. Install many times on kubernetes. EZD RP / LP Backend
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- config
kubeVersion: '>=1.19.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: ezd-backend
sources:
- https://github.com/linuxpolska/ezd-rp.git
type: application
version: 1.7.0
