annotations:
  catalog.cattle.io/display-name: CRDs for LP Backend
  catalog.cattle.io/namespace: default
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: ezd-crd
apiVersion: v2
appVersion: 1.2025.21.7
dependencies:
- condition: global.rabbitmq.deploy
  name: rabbitmq-cluster-operator  
  alias: rabbitmq-operator
  repository: https://charts.bitnami.com/bitnami
  version: 4.4.11
- condition: global.postgresql.deploy
  name: cloudnative-pg
  repository: https://cloudnative-pg.github.io/charts
  #name: cnpg-operator
  #alias: cloudnative-pg
  #repository: https://sourcemation.github.io/charts
  version: 0.23.2
- condition: global.redis.deploy
  name: redis-operator
  repository: https://ot-container-kit.github.io/helm-charts 
  version: 0.20.1
description: Set of operators and CRDs for LP Backend
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
- ezd
- ezdrp
- ezd-rp
- backend
- databases
kubeVersion: '>=1.19.0-0'
maintainers:
- email: biuro@linuxpolska.com
  name: Linux Polska
name: ezd-crd
sources:
- https://github.com/linuxpolska/ezd-rp.git
type: application
version: 1.7.0
