{{- if ( .Values.global.mongodb.deploy ) }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
  labels:
    {{- include "ezd-backend.labels" . | nindent 4 }}
type: Opaque
data:
  EZD_INTERNAL_MONGO_USER: {{ default ( "root" ) | b64enc }}
  EZD_INTERNAL_MONGO_PASSWORD: {{ include "ezd-backend.password" .Values.mongodb.auth.rootPassword | b64enc }}
  EZD_INTERNAL_MONGO_HOST: {{ (index .Values "mongodb" "fullnameOverride") | b64enc  }}
  EZD_INTERNAL_MONGO_PORT: {{ (index .Values "mongodb" "service" "port") | b64enc }}

{{- end }}
